version: 2

sources: 
  - name: olist_raw
    database: olist-dbt-bigquery
    schema: olist_raws
    tables:
      - name: customers
      - name: geolocation
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: orders
      - name: products
      - name: sellers
      - name: product_category_name_translation